apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: <bucketName>
  annotations:
    crossplane.io/external-name: <bucketName>
spec:
  forProvider:
    location: EU
  providerConfigRef:
    name: default
